server:
  port: 8080
spring:
  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
      database: ${DB_NAME}
  application:
    name: library
mongock:
  change-logs-scan-package:
    - ru.otus.library.changelogs
  enabled: true
  runner-type: InitializingBean

hystrix:
  dashboard:
    proxy-stream-allow-list: '*'
  command:
    books:
      circuitBreaker:
        errorThresholdPercentage: 50
        requestVolumeThreshold: 10
        sleepWindowInMilliseconds: 6000
      metrics:
        rollingStats:
          timeInMilliseconds: 15000
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    enabled: true
  instance:
    instance-id: ${spring.application.name}:${server.port}
    leaseExpirationDurationInSeconds: 90
    leaseRenewalIntervalInSeconds: 30
    prefer-ip-address: true
  server:
    eviction-interval-timer-in-ms: 15000

management:
  endpoints:
    web:
      exposure:
        include: '*'